### PR TITLE
Update JsonUtils.psm1

### PR DESCRIPTION
**Pull request by Szeraax**

### CODE REVIEW

**Comment by ghost** [comment]
Looks good! I'm on afk now, will try to approve tomorrow. I'm out of PowerShell ecosystem now, do u mind if I make you co owner? I also will need publish it in the PSGallery afterwards.

**Comment by Szeraax** [comment]
Ya, add me as owner is fine. Thanks! Is choovick out of the picture too?

**Comment by ghost** [comment]
Oh lol, I'm choovick, just using work account on mobile....

**Comment by choovick** [comment]
Don't remember all details of PSGallery, but I think I can publish it after this is merged...

Can you update version to `0.2.0` here? https://github.com/choovick/ps-jsonutils/blob/master/JsonUtils/JsonUtils.psd1#L7

Tests looks good:
image

**Comment by Szeraax** [comment]
In PowerShellGallery.com, you can add me as an owner for this package and I can publish it. That would be a good test. I plan to leave you on as an owner of the package.

**Comment by ghost** [comment]
~@Szeraax what's your ID there? try publishing yourself after I invite you~

All good, found you (same ID). Invite sent.

**Comment by Szeraax** [comment]
Will have to try it tonight. Yup, that's the right ID.

**Pull request merged**
